### PR TITLE
Warnings as errors

### PR DESCRIPTION
**Pull request by turion**
I think it would be a good idea to catch GHC warnings early on. This PR makes sure CI fails when there is a GHC warning.

CC @idontgetoutmuch

### CODE REVIEW

**Comment by turion** [comment]
Naturally, the build fails because there are warnings in the current tree.

**Review by idontgetoutmuch — APPROVED** [review]

**Comment by idontgetoutmuch** [comment]
@turion can you fix the warning and then resubmit?

**Comment by turion** [comment]
@idontgetoutmuch can we not merge yet? It would be nice to merge without squashing.

**Comment by idontgetoutmuch** [comment]
Great! Thanks for doing this.

**Pull request merged**
