### PR TITLE
feature/use new jupyterwith

### PR DESCRIPTION
**Pull request by djacu**
Updated to use the latest version of jupyterWith.
~Still waiting on https://github.com/tweag/jupyterWith/pull/358 to go through so the new iHaskell kernel is available.~
PR is ready for review.

### CODE REVIEW

**Comment by mknorps** [comment]
@djacu How should you run jupyter lab?
I am running `jupyter-lab` from within the shell and I got a repeated message:
```
jupyterWith needs to build JupyterLab.
jupyterWith needs to build JupyterLab.
jupyterWith needs to build JupyterLab.
```

**Comment by djacu** [comment]
@mknorps sorry I just saw your message. Are you still getting that repeated message?

**Comment by mknorps** [comment]
> @mknorps sorry I just saw your message. Are you still getting that repeated message?

Yes. It looks like similar to https://github.com/tweag/jupyterWith/issues/341.

**Review by mknorps — APPROVED** [review]
Thank you!

**Comment by turion** [comment]
Thanks a lot! Can you rebase, and I'll look into this?

**Comment by turion** [comment]
I took the liberty to rebase, resolve conflicts, and push force.

**Comment by turion** [comment]
I have superficially checked that even after the rebase, all changes to `flake.lock` are additions or updates.

**Comment by turion** [comment]
The changes to the notebook seem fine.

**Pull request merged**
