### PR TITLE
Allow different versions of GHC on CI

### PR DESCRIPTION
**Pull request by turion**
This adds a list of GHC versions in `flake.nix` which can be extended. Each of these versions is used to build and test the package.

### CODE REVIEW

**Comment by turion** [comment]
Right now every PR fails because of formatting for some reason. I suspect some version of the formatter was increased without running CI completely.

**Comment by turion** [comment]
I'll try to fix in https://github.com/tweag/monad-bayes/pull/269 first.

**Comment by turion** [comment]
@idontgetoutmuch If you're ok with this we can at least claim to support two GHC versions now :)

**Review by idontgetoutmuch — APPROVED** [review]
Great - thanks for doing this :-)

**Pull request merged**
