### PR TITLE
Use custom stream of trees type in lazy sampler

### LINKED ISSUE #184: Why use Lists for streams in the lazy sampler?
Just a small nitpick. Wouldn't it be clearer to use a stream type in the definition of trees?

```
data Stream a = Stream a (Stream a)
data Tree = Tree Double (Stream Tree)
```

Otherwise, it is too easy to mistake the `Tree` for a [rose tree](https://en.wikipedia.org/wiki/Rose_tree).

If you're interested, I can send a PR for this.

### PR DESCRIPTION
**Pull request by turion**
Fixes #184

### CODE REVIEW

**Comment by reubenharry** [comment]
Why not use a library definition of a stream? Unnecessary overhead?

**Review by reubenharry — APPROVED** [review]

**Comment by turion** [comment]
> Why not use a library definition of a stream? Unnecessary overhead?

Yes, I looked into several libraries. Some were well-built, but complex like https://hackage.haskell.org/package/streaming-0.2.3.1/docs/Streaming.html, some were simple enough like https://hackage.haskell.org/package/streams but seem not active enough to be a reliable dependency.

**Comment by turion** [comment]
If you want, I can rewrite with `streaming`. I think that would be my first choice.

**Comment by turion** [comment]
...but I think that at this point, a dependency would be unnecessary overhead. We're not using any fancy stream manipulation functions (yet).

**Pull request merged**
