### PR TITLE
Make transformer naming idiomatic. Fixes #189. Fixes #242.

### LINKED ISSUE #189: T in the transformer names
Sequential -> SequentialT
Traced -> TracedT
Population -> PopulationT
run[X] -> run[X]T

This helps Haskellers understand what is going on better.
```[tasklist]
### Tasks
- [ ] Sequential
- [ ] Traced
- [ ] Population
- [ ] Weighted
- [ ] Density
- [ ] Sampler
- [ ] run* functions
```

### LINKED ISSUE #242: Inconsistent naming of monad transformer functions
Most monad transformers have the following pattern: https://github.com/tweag/monad-bayes/blob/110e040099d7f1dc1c5f0bd6170fed759897a5b6/src/Control/Monad/Bayes/Weighted.hs#L48

There are two functions that interpret/run/destruct a transformer `FooT`, one called `foo` and `runFoo`. This is an unusual convention. The most common convention, as far as I'm aware, is the following:

* Call the full transformer `FooT`
* Declare it as a newtype record, and call the record accessor function `runFooT`, `getFooT` or `unFooT`:
  ```haskell
  newtype FooT m a = FooT { runFooT :: m (frobnicate a) }
  ```
* Possibly declare an interpretation function `runFooT`, `execFooT`, ...
* Declare a type synonym `type Foo a = FooT Identity a`
* Write a constructor `foo :: frobnicate a -> Foo a` that is analogous to `FooT`
* Write a destructor `runFoo :: Foo a -> frobnicate a` analogous to `runFooT`

That way, the `runFoo` functions have the role of destructors, while the `foo` functions are constructors.

The constructor function for `Weighted`, coincidentally is called `withWeight`:

https://github.com/tweag/monad-bayes/blob/110e040099d7f1dc1c5f0bd6170fed759897a5b6/src/Control/Monad/Bayes/Weighted.hs#L65

From that function name, I wouldn't expect a constructor, but rather a function that applies a transformation staying inside the monad.

The question is whether we want to pull these conventions straight. It would cause breakage and trigger a major version release.

### PR DESCRIPTION
**Pull request by turion**
CC @reubenharry @idontgetoutmuch . Can you review? I'd like to merge and release (as version 1.2.0) before publishing my blog post, so the blog post can be with the new conventions.

* [x] Fix the notebooks and tutorials.

### CODE REVIEW

**Review by reubenharry — APPROVED** [review]
Looks good!

**Review by idontgetoutmuch — APPROVED** [review]

**Comment by idontgetoutmuch** [comment]
@reubenharry you will have to edit your tutorial maybe?
@turion Lint is failing and there are some conflicts.

**Comment by turion** [comment]
> you will have to edit your tutorial maybe?

I tried to take care of this and changed all the md files. I'm assuming this is enough?

> Lint is failing and there are some conflicts.

Yes, I can fix that.

**Comment by turion** [comment]
> > you will have to edit your tutorial maybe?
> 
> I tried to take care of this and changed all the md files. I'm assuming this is enough?

@reubenharry can you clarify whether the files `docs/docs/notebook/*.html` need to be adapted? Are they autogenerated? If yes, how?

**Comment by reubenharry** [comment]
To my recollection, they are not autogenerated - I just exported and saved the notebooks manually.

**Comment by turion** [comment]
Ah, so I need to regenerate them before merging?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by reubenharry** [comment]
In theory, yes, by manually exporting each and copying it to the appropriate folder. I don't object if you don't though, I know it's a slight hassle.

**Comment by turion** [comment]
What I haven't understood is whether netlify serves the *.html directly, or whether it regenerates them from the *.md. If the latter, I'd in fact recommend removing the *.html from the repo.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by reubenharry** [comment]
For the notebooks or docs? It's been a while, but I think it builds the docs from the md (using mkdocs), but the notebooks go straight from ipynb to html.

**Comment by turion** [comment]
> In theory, yes, by manually exporting each and copying it to the appropriate folder.

I'm trying to do that with `jupyter-nbconvert`, so far without luck. How do you do that?

**Comment by turion** [comment]
As far as I understand, the only thing that is not automatic is how the html are generated from the notebooks. It would be good to merge https://github.com/tweag/monad-bayes/pull/302 first to make sure I don't break the documentation.

**Comment by turion** [comment]
In fact I want to merge https://github.com/tweag/monad-bayes/pull/304 first, which superseded #302.

**Pull request merged**
