### PR TITLE
Rename

### PR DESCRIPTION
**Pull request by reubenharry**
Re issue #197. Obviously this is quite a large breaking change, so would merit a new release. But I think especially for didaction purposes, the new names are much more clear. It's confusing to have to explain that `MonadSample` doesn't have anything inherently to do with sampling, or that `MonadInfer` doesn't have anything inherently to do with inference.

### CODE REVIEW

**Comment by idontgetoutmuch** [comment]
How does this relate to https://github.com/tweag/monad-bayes/pull/196? We said there that we would commit https://github.com/tweag/monad-bayes/pull/179 first to avoid a more complicated rebase. So I assume we won't merge this until afterwards?

**Comment by reubenharry** [comment]
> How does this relate to #196? We said there that we would commit #179 first to avoid a more complicated rebase. So I assume we won't merge this until afterwards?

That sounds right to me

**Comment by idontgetoutmuch** [comment]
So I think this is now ok to merge? @reubenharry @mknorps?

**Comment by reubenharry** [comment]
Needs rebase. I will do that now. Easier actually to just redo from main.

**Pull request closed without merging**
