### PR TITLE
Fix cachix

### LINKED ISSUE #273: Nix cache on CI doesn't work properly
Recent PRs (see https://github.com/tweag/monad-bayes/pull/271#issuecomment-1550907396, https://github.com/tweag/monad-bayes/actions/runs/4996034119/jobs/8948715375) took a very long time to complete on CI. The problem was probably made more visible by adding multiple GHC versions to CI (https://github.com/tweag/monad-bayes/pull/266).

In theory, we have a Cachix setup (https://github.com/tweag/monad-bayes/blob/master/.github/actions/nix-common-setup/action.yml#L11), but in practice it doesn't work because we keep rebuilding the same packages in subsequent runs:

For example, https://github.com/tweag/monad-bayes/actions/runs/4996034119/jobs/8948715375?pr=271#step:6:1134 should have been cached because it was built in https://github.com/tweag/monad-bayes/actions/runs/4992638711/jobs/8940645540#step:6:1135 already.

Probably, the Cachix configuration is not respected properly: 
https://github.com/tweag/monad-bayes/actions/runs/4996034119/jobs/8948715375?pr=271#step:6:7
```
warning: ignoring untrusted flake configuration setting 'extra-substituters'.
Pass '--accept-flake-config' to trust it
warning: ignoring untrusted flake configuration setting 'extra-trusted-public-keys'.
Pass '--accept-flake-config' to trust it
```

Other possibilities to explore if this is not the cause: The cachix cache might be too small, its key or configuration has changed since it was set up. Either way we should make sure that maintainer of this repo here can configure the Cachix.

CC @idontgetoutmuch @reubenharry

### PR DESCRIPTION
**Pull request by turion**
Fixes #273

### CODE REVIEW

**Comment by turion** [comment]
This seems to actually push objects to the cache.

```
Post job cleanup.
Cachix: push
  /home/runner/work/_actions/cachix/cachix-action/v12/dist/main/push-paths.sh cachix  tweag-monad-bayes  
  compressing using zstd and pushing /nix/store/4w4b4mxfhdc9lf3rsf4qqa9z8xnijbxl-source (26.27 KiB)
  compressing using zstd and pushing /nix/store/7rvyhm99h13ddfwblbixhr7iy9mzr4zj-cabal-fmt-0.1.6 (6.79 MiB)
  compressing using zstd and pushing /nix/store/5lzm0zkydfl9bs19zs0lbr7y0qsxh613-source (8.03 KiB)
  compressing using zstd and pushing /nix/store/9p17l6hmyz32hjma72nw6dfqxfnqk8x8-source (53.46 KiB)
  compressing using zstd and pushing /nix/store/gsslxw2mhiygis23y7nrizbpjl1pgbaq-source (162.64 KiB)
  compressing using zstd and pushing /nix/store/kz15p1pxm5dw3hnay3bnqhz4mvsg8jyl-source (34.86 MiB)
  compressing using zstd and pushing /nix/store/plcgf3d938380z6qaim2fa22gna3c12l-pre-commit-run (112.00 B)
  compressing using zstd and pushing /nix/store/fxf5927vw1wl2ap0lhr72fx3jbj1wmwj-source (127.23 KiB)
  compressing using zstd and pushing /nix/store/qwk3nqcb5k3y51k1kbrqamgcp83544zl-pre-commit-config.json (1.60 KiB)
  compressing using zstd and pushing /nix/store/ymdgrjb15pg6w0dhwx006kyzngrmnv4y-cabal-fmt-0.1.6-bin (3.94 MiB)
  All done.
```

**Comment by turion** [comment]
And it can read as well:

```
Run nix --print-build-logs build .#pre-commit --accept-flake-config
  nix --print-build-logs build .#pre-commit --accept-flake-config
  shell: /usr/bin/bash -e {0}
  env:
    NIX_PATH: nixpkgs=channel:nixos-unstable
  
copying path '/nix/store/4w4b4mxfhdc9lf3rsf4qqa9z8xnijbxl-source' from 'https://tweag-monad-bayes.cachix.org/'...
copying path '/nix/store/fxf5927vw1wl2ap0lhr72fx3jbj1wmwj-source' from 'https://tweag-monad-bayes.cachix.org/'...
copying path '/nix/store/zjpd6dn9kza8zl3l17cwgyifsxbvi3nb-source' from 'https://cache.nixos.org/'...
```

**Comment by turion** [comment]
Now the question is whether the common nix setup already worked in the first place. And if yes, if `--accept-flake-config` is needed at all. And if no, why we never saw a benefit of caching before. Maybe we simply never populated the cache. To do so, we could for example run `master` after every PR when it's merged.

**Comment by turion** [comment]
> Now the question is whether the common nix setup already worked in the first place

Yes it does, see https://github.com/tweag/monad-bayes/actions/runs/5004889063/jobs/8968073752?pr=277.

**Comment by turion** [comment]
> And if yes, if `--accept-flake-config` is needed at all.

```
warning: ignoring untrusted flake configuration setting 'extra-substituters'.
Pass '--accept-flake-config' to trust it
warning: ignoring untrusted flake configuration setting 'extra-trusted-public-keys'.
Pass '--accept-flake-config' to trust it
copying path '/nix/store/4w4b4mxfhdc9lf3rsf4qqa9z8xnijbxl-source' from 'https://tweag-monad-bayes.cachix.org/'...
copying path '/nix/store/fxf5927vw1wl2ap0lhr72fx3jbj1wmwj-source' from 'https://tweag-monad-bayes.cachix.org/'...
```
So no, it isn't.

> And if no, why we never saw a benefit of caching before. Maybe we simply never populated the cache.

Yes, I forgot that the cachix action part was commented all the time.

**Comment by turion** [comment]
@idontgetoutmuch @reubenharry can you review?

**Comment by reubenharry** [comment]
I'll defer to @idontgetoutmuch , since I don't know any nix.

**Comment by idontgetoutmuch** [comment]
> I'll defer to @idontgetoutmuch , since I don't know any nix.

In the kingdom of the blind...

@turion can we talk for 10 minutes? It looks fine but I really don't know much about CI.

**Review by idontgetoutmuch — APPROVED** [review]

**Pull request merged**
